services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\Module\tnetc\Repository\TimeConditionRepository:
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository
    arguments:
      $timeGroupRepository: '@TelNowEdge\Module\tnetc\Repository\TimeGroupRepository'
      $calendarHelper: '@TelNowEdge\Module\tnetc\Helper\CalendarHelper'
      $dayNightRepository: '@TelNowEdge\Module\tnetc\Repository\DayNightRepository'
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\Module\tnetc\Repository\TimeGroupRepository:
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\Module\tnetc\Repository\DayNightRepository:
    parent: TelNowEdge\FreePBX\Base\Repository\AbstractRepository
    autowire: true
    autoconfigure: false
    public: true
