services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\Module\tnetc\Helper\CalendarHelper: ~

  TelNowEdge\Module\tnetc\Manager\DestinationManager:
    arguments:
      - '@TelNowEdge\Module\tnetc\Repository\TimeConditionRepository'
