services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  TelNowEdge\Module\tnetc\EventSubscriber\TimeConditionSubscriber:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "kernel.event_subscriber"

  TelNowEdge\Module\tnetc\EventSubscriber\TimeConditionBlockSubscriber:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - "kernel.event_subscriber"
